### ISSUE TITLE
Instructions on Getting Started with Windows

### ISSUE THREAD

**Issue by chenglou** [reasonml/reasonml.github.io#195]
This should turn into a doc page in the future, but I'd like to gather some feedback on Reason on Windows. In the meantime we'll link this from the doc site.

Context:

Reason on Windows is complicated.

- BuckleScript (bs-platform) 1.9.3 is verified to work well on Windows (1.9.2 had some bugs)
- Reason-cli, through which the important binaries merlin, ocamlmerlin_reason and refmt are installed, doesn't work on Windows.
- OPAM, not verified. But we'll focus on the JS story in this issue.

Workarounds:

- For merlin, a temporary substitute is to have [bsb errors piped into vscode](https://github.com/reasonml-editor/vscode-reasonml#bsb). Bsb is the build system from bs-platform, which works with Windows. Although apparently

**Comment by superherointj** [comment]
**## [WIP. This is a draft I am and will be editing. I'm testing instructions on a clean Windows environment. NOT READY. Please, just wait.]**

**Comment by yawaramin** [comment]
Here is what I did to get OCaml + Merlin working. Haven't tried Reason.

- Install WSL with https://msdn.microsoft.com/en-us/commandline/wsl/install_guide
- Restart
- Install node using the Windows installer
- Add the following to my user account's path:
  - `C:\Program Files\nodejs`
  - `%APPDATA\npm`
- At the Windows command prompt: `npm i -g npm ocaml-on-windows bs-platform`
  - `npm` to get version 5.4.2
  - `ocaml-on-windows` took a while to install
- At the WSL `bash` prompt: `opam switch 4.02.3; eval $(opam config env); opam install merlin`
- Install VSCode & @hackwaly 's OCaml extension
- Add the following to VSCode settings: `"ocaml.merlinPath": "ocamlmerlin.cmd"`
- At the Windows command prompt: `bsb -init test-proj`
- Open VSCode to `test-proj` directory and check out the type hints etc.

This is I think the bare minimum to get OCaml and Merlin working on Windows, thanks to WSL and @fhelwanger 's scripts (the `.cmd` files) mapping each OCaml toolchain command to its corresponding command in the WSL installation.

**Comment by fhelwanger** [comment]
@superherointj Thanks for writing this!

I think that everything inside `On "Bash on Ubuntu on Windows":` isn't necessary. I wrote that [preinstall script](https://github.com/fhelwanger/ocaml-on-windows/blob/d32bf1f036d60733ae05a422570cf6f62d477ad0/bin/preinstall.bat) to do these steps automatically when installing ocaml-on-windows. If there's anything missing there, I think we can add to preinstall instead of requiring users to run manually.

Regarding it not working when there's a Merlin file at project root, unfortunately I don't know how to solve. I tried to investigate it for some time, but couldn't figure out how to solve it. I'm new to ocaml and reason too. Actually, I created ocaml-on-windows so I could learn reason 😄

**Comment by fhelwanger** [comment]
@yawaramin I think that using the last version you don't need to configure `ocamlmerlin.cmd` path, since this is merged https://github.com/freebroccolo/ocaml-language-server/pull/31.

**Comment by superherointj** [comment]
@jchavarri Suggested to run Bucklescript on WSL only. And that fixed the merlin path problem on a 
Windows instance I've got Merlin working and no errors with Merlin file with Unix paths (WSL BSB generated). It seems we can't go half way with WSL. Must go all in. I still need to do more tests.

**Comment by yawaramin** [comment]
@fhelwanger thanks! I will try the Reason VSCode extension next.

@superherointj for me BuckleScript (1.9.3) has been working at the normal Windows command prompt. There might be some other root cause...

**Comment by jchavarri** [comment]
@yawaramin One of the outcomes from the convos with @superherointj is that in order for Merlin to be happy (and thus, vscode Reason extension to work properly), Bucklescript needs to be installed in WSL as well.

I've created https://github.com/fhelwanger/ocaml-on-windows/issues/17 to propose to add it to `ocaml-for-windows`.

**Comment by yawaramin** [comment]
@jchavarri it might be specifically a Reason thing, Merlin has been happy with BuckleScript on the Windows command prompt for OCaml syntax. I'll try and report back on that.

**Comment by chenglou** [comment]
@fhelwanger

> @yawaramin I think that using the last version you don't need to configure `ocaml.merlinPath` path, since this is merged https://github.com/freebroccolo/ocaml-language-server/pull/31.

He was talking about https://github.com/hackwaly/vscode-ocaml, which doesn't use ocaml-language-server yet. Relevant issue: https://github.com/hackwaly/vscode-ocaml/issues/114

**Comment by fhelwanger** [comment]
@chenglou You're right! Thanks for pointing out.

**Comment by chenglou** [comment]
Update: apparently as of last week, the new release of merlin supports Windows! Though I've heard it works with ocaml, but not reason

**Comment by Mikk36** [comment]
If bs-platform fails to install in WSL with permissions issue, configure npm to store global packages in a user-writable location (ie, not in /usr) and install bs-platform without prepending it with sudo.
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by fhelwanger** [comment]
@Mikk36 You can use https://github.com/fhelwanger/ocaml-reason-wsl to automate this process.

I released a new version this week that installs bs-platform too.

Everything that is installed can be found here: https://github.com/fhelwanger/ocaml-reason-wsl/blob/master/bin/preinstall.bat

**Comment by chenglou** [comment]
Some info on an alternative, using Docker: https://gist.github.com/pbiggar/cce9b958704c6cadd9597b717bc18c4d

Tested by one person

**Comment by superherointj** [comment]
## Work In Progress - You may ignore it ##

Notes:
- Merlin.2.5.4 is working w/ Reason extension on Windows and Merlin.3.0.3 is not (still unknown why).
- Only a [path translation fix](https://github.com/freebroccolo/ocaml-language-server/pull/44) for VSCode extension is missing but the update is automatic and the fix is coming next release.

### Solution 2: Windows Native (Not ideal yet - Skip it) ###

How it would work
  - Instead of running Merlin on Windows native, it is possible to have BSB errors piped into VSCode, solving the diagnosis part provided by Merlin, but not the autocomplete, jump-to-definition.
For `refmt`, it is possible to use `bsrefmt` that comes with bs-platform, under `node_modules/bs-platform/bin/bsrefmt`. This is BuckleScript's vendor refmt, pinned at 1.13.6 (will be updated soon). Just make your editor point to it.

For now, solution #1 is broken. Skip it. Because:
- ReasonML's VSCode extension requires Merlin for working. Which leads to the case where either Merlin works on Windows (with windows paths in .merlin file) or Merlin has to be disabled. It's absence is not handled gracefully and shows errors. In a future release [Merlin might be optional](https://github.com/reasonml-editor/vscode-reasonml/issues/102). Right now on Windows native neither can be done. (Having it working nor disable it.)

> **If you know how to make this documentation better, reply here, shout at us or just fix it (if you can).
Thanks in advance for helping us make this documentation better.**

### On Watch ###
- VSCode extension
  - 1.0.3 release
  - [Issue #113 WslMode](https://github.com/reasonml-editor/vscode-reasonml/issues/113)
    - Automates bash commands definition
    - Fix translating paths between unix/windows

**Comment by ubsan** [comment]
Attempting to install ocaml on Windows:

(go to Official OCaml distribution, get linked to Hauptmann's installer, download the 64-bit version, attempt to install into `C:\Program Files\OCaml`)

>The installation directory contains a space character. This is not supported. Please choose another directory!

**Comment by superherointj** [comment]
We are doing a fund raise to improve Windows Tooling! Participate!

[https://github.com/facebook/reason/issues/1698](https://github.com/facebook/reason/issues/1698)

**Comment by superherointj** [comment]
### Ongoing efforts ###

# Campaign to improve Windows Tooling #
We are doing a crowd sourced fund raise to improve Windows Tooling for BuckleScript/Reason (development time). Participate!

[https://github.com/facebook/reason/issues/1698](https://github.com/facebook/reason/issues/1698)

**Comment by vramana** [comment]
I would always recommend installing node through [nvm](https://github.com/creationix/nvm) It doesn't have any of the npm permission issues and pretty simple to upgrade and switch node version.

**Comment by Mikk36** [comment]
But, but, nvm doesn't support Windows, which this whole thread is about.

**Comment by superherointj** [comment]
@Mikk36 WSL is unix environment, so `nvm` should work on it. Current guide was tested dozens of times for edge cases and is known to work properly. And works well for most people/needs. While a `nvm` like solution could offer some added benefit to some, it would increase complexity and could lead to new unknown situations/edge cases that would have to be accounted for with new tests and possible improvements. I think we're probably better keeping it simple as it is now. Without requiring an external package or requiring the user to learn a new tool. 

@vramana Still, if you want to test it yourself and document it, it could be added as an option. Would be nice to keep instructions here very precise so newcomers don't have to guess much and lower likelihood of newcomers running into trouble.

**Comment by freebroccolo** [comment]
> I would always recommend installing node through nvm It doesn't have any of the npm permission issues and pretty simple to upgrade and switch node version.

I just want to mention that a lot of people that have been having problems getting language server to work are using `nvm` or one of the alternatives. The problem appears to be that `nvm` does not always set up the environment properly (e.g., for login shells), causing tools to not be found in the PATH, etc. If you look at the `nvm` repo you will see a lot of open issues about this.

I would not recommend using `nvm` by default, especially if there is no particular need. It's much more likely to cause problems with other tooling which is frustrating for both users and maintainers.

**Comment by rainerlopez** [comment]
Follow the guide !
Install Windows Subsystem for Linux (WSL) - FROM THE STORE
lxrun /uninstall /full
restart computer
lxrun /install

In my case, the best option was to clean everything:
Check if you have Node.js installed via "Add or remove programs Tool" and/or via CMD
Check if you have any Distro installed: wslconfig /list /all - If yes, you will need to set the Ubuntu as default: wslconfig /setdefault Ubuntu

The rest was smoothly sweet, pick the manual Opam/OCam and be happy :)

![reason_wsl](https://user-images.githubusercontent.com/1648432/34285592-dc94d25c-e6c1-11e7-8e52-119cb8011c78.jpg)

**Comment by kevinSuttle** [comment]
Is there official documentation on Windows, pre-v10?

**Comment by superherointj** [comment]
@kevinSuttle Not for now. Current workaround uses WSL, which barely works in Win10 latest, using latest version is necessary/recommended.

**Comment by kevinSuttle** [comment]
Fair enough. Thanks!

**Comment by benmp** [comment]
Hello,

I seem to be having some issues.  The steps I completed were:
1) Install WSL
2) Manual install node, npm, reason-cli on WSL
3) Install bs-platform and vs-code plugin

![image](https://user-images.githubusercontent.com/9081154/34805332-c4fc1780-f63a-11e7-9c44-83172e54e21f.png)

![image](https://user-images.githubusercontent.com/9081154/34805345-de0edde8-f63a-11e7-9f9a-82a642ef2fab.png)

When running Vim on this same WSL setup, I can use vim-reason-plus on the LanguageClient-Neovim plugin without issues.

**Comment by isaksky** [comment]
Followed the manual path with opam, having first done a fresh WSL uninstall and reinstall, and I get this:

![image](https://user-images.githubusercontent.com/607986/34807006-7b093bd6-f643-11e7-86b0-c47cba67aa7e.png)

**Comment by superherointj** [comment]
@isaksky Make sure you have the correct Ubuntu WSL environment selected.
Try:
`wslconfig /list /all`
If Ubuntu isn't default. Pick it as default environment with command:
wslconfig /setdefault Ubuntu

**Comment by isaksky** [comment]
@superherointj Ubuntu was the only and default one in the list.

**Comment by superherointj** [comment]
@isaksky Can you come to Discord and PM me? I don't know why this is going on for you. But would be nice if we could *try* to discover a solution for this. Also bear with me If I'll be asking stupid questions or offering random crap ideas (that might be somewhat silly) until we reach hopefully a working solution.

**Comment by patoncrispy** [comment]
`npm install -g ocaml-reason-wsl` won't work if you have fish shell configured. I disabled it in my .bashrc file and it worked fine.

**Comment by mickeyvip** [comment]
The last bullet "Open VSCode on demoapp folder and test it" - how do I do it?

The project is created in the WSL window ("Ubuntu")
The VSCode runs on Windows
How do I open WSL's folder on Windows?

**Comment by superherointj** [comment]
VSCode runs in Windows environment indeed. On it, open a folder let's say as an example: `c:\myproject\`
And this is accessible in WSL. In WSL try to open: `/mnt/c/myproject/` and it will open...

**Comment by superherointj** [comment]
@mickeyvip Open VSCode in a folder, e.g: `C:\myproject\`
In WSL open: `/mnt/c/myproject/`
Happy coding.

**Comment by isaksky** [comment]
@mickeyvip Sounds like you are creating the project in WSL's special area of the file system, which you don't want to do. Just do `/mnt/c/something..`, like above.

**Comment by mickeyvip** [comment]
@superherointj, thank you.
I did what you suggested and had more progress.
Now I have this:
![image](https://user-images.githubusercontent.com/220427/34903361-46be926c-f838-11e7-9201-8760a5547d9f.png)

While I do have the intellisense saying `(module TodoApp-Demoapp)` and  the file:
![image](https://user-images.githubusercontent.com/220427/34903366-5952f0bc-f838-11e7-990f-ee23a7e0dcfe.png)

**Comment by superherointj** [comment]
@mickeyvip, PM me on Discord.

**Comment by superherointj** [comment]
@benmp Extension author freebroccolo answered:
`That error message would indicate some communication problem between the vscode extension and the server but I'm surprised that it would happen unless somehow they've installed an obsolete version of one or the other`
Make sure you have latest version of extension/ocaml-language-server. 
Also check if VSCode is 64-bit (seem already some odd errors in 32-bit VSCode)
Not sure this is going to solve your issue.
The main support channel for this is Discord #editorsupport , feel free to say Hi there.

**Comment by vinaydate** [comment]
My installation fails.

Some background: I had installed ocaml for windows earlier (few months back) on this machine, but did not get full tooling in vscode. Had abandoned ReasonML due to time constraints. 

Now,  with this new guide, thought to give this a chance again. I am getting following error in log file:

```
54 verbose stack Error: ocaml-reason-wsl@0.1.1 preinstall: `bin\preinstall.bat`
54 verbose stack Exit status 2
54 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
54 verbose stack     at EventEmitter.emit (events.js:160:13)
54 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
54 verbose stack     at ChildProcess.emit (events.js:160:13)
54 verbose stack     at maybeClose (internal/child_process.js:943:16)
54 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
55 verbose pkgid ocaml-reason-wsl@0.1.1
```

I have tried both ```npm install -g ocaml-reason-wsl``` and ```npm install -g fhelwanger/ocaml-reason-wsl```

**Comment by kyldvs** [comment]
@superherointj Why are the recommended commands `bash -ic` instead of `bash -c`, the former drops you into an interactive terminal and doesn't seem to run the command, the latter seems to work as expected. Should the guide be updated?

![screenshot 53](https://user-images.githubusercontent.com/1830497/36636612-ead71114-197e-11e8-91b3-8d2c8df33aec.png)

**Comment by zploskey** [comment]
@kyldvs Interesting. When I run `bash -ic "refmt --version"` on Linux it outputs the version and does not leave me in a new running shell. I'm not sure what the point of using `-i` is here.
```shell
$ bash --version
GNU bash, version 4.4.19(1)-release (x86_64-redhat-linux-gnu)
```
Not sure what is used for bash in WSL, but it sounds like the we probably ought to use `bash -c` in the instructions.

**Comment by ssrb** [comment]
Seems no longer working after latest VS code upgrade on Windows
![error](https://user-images.githubusercontent.com/1386579/37327994-5bdf93dc-26fd-11e8-94d8-10eb1ddef8c3.PNG)

**Comment by superherointj** [comment]
![app re - assets - visual studio code](https://user-images.githubusercontent.com/5861043/37401626-72dc624e-2767-11e8-9271-e43b99decd70.jpg)

Opened issue at: [https://github.com/reasonml-editor/vscode-reasonml/issues/186](https://github.com/reasonml-editor/vscode-reasonml/issues/186)

**Comment by matystl** [comment]
@superherointj  Name of extension for vscode has changed name to "OCaml and Reason IDE" and you will not find it through search with string "vscode-reasonml" nor "reasonml" would be nice to update second post

**Comment by superherointj** [comment]
@zploskey "bash -ci" is a command for running in CMD prompt (Windows environment), meant for Windows not Linux. Running bash on Linux is not same thing. In our use case, Windows requires "bash -ci".

**Comment by matystl** [comment]
reference to `npm install -g reason-cli@3.1.0-linux` should be updated to `
npm install -g reason-cli@3.2.0-linux`

**Comment by robkuz** [comment]
hey,

I am using Reason on Windows 10 (WSL) and I followed the instructions here  - at least I think so
but I get this error
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle demoapp@0.1.0~prestart: demoapp@0.1.0
6 info lifecycle demoapp@0.1.0~start: demoapp@0.1.0
7 verbose lifecycle demoapp@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle demoapp@0.1.0~start: PATH:...
9 verbose lifecycle demoapp@0.1.0~start: CWD: reason-test/demoapp
10 silly lifecycle demoapp@0.1.0~start: Args: [ '-c', 'bsb -make-world -w' ]
11 silly lifecycle demoapp@0.1.0~start: Returned: code: 2  signal: null
12 info lifecycle demoapp@0.1.0~start: Failed to exec start script
13 verbose stack Error: demoapp@0.1.0 start: `bsb -make-world -w`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid demoapp@0.1.0
15 verbose cwd /reason-test/demoapp
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error demoapp@0.1.0 start: `bsb -make-world -w`
22 error Exit status 2
23 error Failed at the demoapp@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
Intersting enough I have 2 other machines where this worked w/o problems. Does anybody see the error?

**Comment by robkuz** [comment]
hey,

I am using Reason on Windows 10 (WSL) and I followed the instructions here  - at least I think so
but I get this error
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle demoapp@0.1.0~prestart: demoapp@0.1.0
6 info lifecycle demoapp@0.1.0~start: demoapp@0.1.0
7 verbose lifecycle demoapp@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle demoapp@0.1.0~start: PATH:...
9 verbose lifecycle demoapp@0.1.0~start: CWD: reason-test/demoapp
10 silly lifecycle demoapp@0.1.0~start: Args: [ '-c', 'bsb -make-world -w' ]
11 silly lifecycle demoapp@0.1.0~start: Returned: code: 2  signal: null
12 info lifecycle demoapp@0.1.0~start: Failed to exec start script
13 verbose stack Error: demoapp@0.1.0 start: `bsb -make-world -w`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid demoapp@0.1.0
15 verbose cwd /reason-test/demoapp
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error demoapp@0.1.0 start: `bsb -make-world -w`
22 error Exit status 2
23 error Failed at the demoapp@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
Intersting enough I have 2 other machines where this worked w/o problems. Does anybody see the error?

**Comment by amsterdamharu** [comment]
If this is still needed for Windows then would it be a good idea to mention this in the documentation [here](https://reasonml.github.io/docs/en/installation) and [here](https://reasonml.github.io/reason-react/docs/en/installation)?

**Comment by Jonas164** [comment]
ocaml 4.02.3 is severly outdated and I require ocaml 4.05 or greater. Is there a known solution to get merlin to work with WSL and VSCode with Ocaml >= 4.05 ? If yes, how? Simply switching to a newer ocaml version does not work.

**Comment by robkuz** [comment]
I got it running with installing X-Windows and running VSCode on WSL. However you better have a powerful machine. It ain't exactly fast

**Comment by Jonas164** [comment]
That does not seem much better than just using a Unix-VM. Both, X-Windows and a VM are not enjoyable on my laptop though

**Comment by hikurangi** [comment]
No doubt you're all aware, but especially for the benefit of people coming across this thread later, using `reason-cli` tools with the [remote server versions of vscode](https://code.visualstudio.com/docs/remote/wsl) on Windows 10 should now be fairly painless, and quite close to the regular Linux experience.

**Comment by emileber** [comment]
@amsterdamharu as the project grows, `jaredly.reason-vscode` extension will eventually fail with _"Command line is too long"_: https://github.com/jaredly/reason-language-server/issues/262
