### ISSUE TITLE
Error install bs-platform

### ISSUE THREAD

**Issue by rajatdhoot123** [reasonml/reasonml.github.io#318]
Unable to install with sudo npm install -g bs-platform

Log file Attached
[log_error.txt](https://github.com/reasonml/reasonml.github.io/files/1705698/log_error.txt)

rajat@LV:~/projects/reason $ sudo npm install -g bs-platform
/usr/bin/bsb -> /usr/lib/node_modules/bs-platform/lib/bsb
/usr/bin/bsc -> /usr/lib/node_modules/bs-platform/lib/bsc
/usr/bin/bsrefmt -> /usr/lib/node_modules/bs-platform/lib/bsrefmt

> bs-platform@2.1.0 postinstall /usr/lib/node_modules/bs-platform
> node scripts/install.js

fs.js:768
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EACCES: permission denied, rename '/usr/lib/node_modules/bs-platform/vendor/ninja-build/ninja.linux64' -> '/usr/lib/node_modules/bs-platform/lib/ninja.exe'
    at Object.fs.renameSync (fs.js:768:18)
    at setUpNinja (/usr/lib/node_modules/bs-platform/scripts/install.js:70:12)
    at Object.<anonymous> (/usr/lib/node_modules/bs-platform/scripts/install.js:161:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bs-platform@2.1.0 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bs-platform@2.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rajat/.npm/_logs/2018-02-08T04_17_20_237Z-debug.log

**Comment by glennsl** [comment]
This is an error with BuckleScript. You should report it on the BuckleScript repo instead: https://github.com/BuckleScript/bucklescript
