### ISSUE TITLE
Error: Couldn't find preset "env" relative to directory

### ISSUE THREAD

**Issue by sorawee** [reasonml/reasonml.github.io#405]
Here's what I get when I follow the instruction to run the site locally:

```
$ npm install
$ npm start
> reason-site@ start /path/to/reasonml.github.io/website
> docusaurus-start

Docusaurus server started on port 3000
LiveReload server started on port 35729
Error: Couldn't find preset "env" relative to directory "/path/to/reasonml.github.io/website/core"
    at /path/to/reasonml.github.io/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/path/to/reasonml.github.io/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/path/to/reasonml.github.io/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/path/to/reasonml.github.io/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/path/to/reasonml.github.io/website/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/path/to/reasonml.github.io/website/node_modules/babel-register/lib/node.js:103:45)
    at loader (/path/to/reasonml.github.io/website/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/reasonml.github.io/website/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
```

I fixed this by installing `babel-preset-env`. Shouldn't this be a part of `package.json` by default?

**Comment by kevinsimper** [comment]
I got the same error and installing the babel-preset-env as you say fixed it
