### ISSUE TITLE
Setup on Windows

### ISSUE THREAD

**Issue by mishaszu** [reasonml/reasonml.github.io#571]
I am not able to setup reason for Visual Studio code.
I followed instruction: #195
I also changed configs for `zsh`: #547

While `zsh -ic 'ocamlmerlin -version` returns:
```
The Merlin toolkit version 2.5.4, for Ocaml 4.02.3
```
I am getting error in vs-code output:
```
/home/misha-think/.vscode-server/extensions/freebroccolo.reasonml-1.0.38/node_modules/ocaml-language-server/bin/server/processes/merlin.js:34
                throw error;
                ^

Error: spawn wsl zsh -ic ocamlmerlin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Error - 7:58:23 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by mishaszu** [comment]
After the [correct installation of `bs-platform` on WSL](https://github.com/BuckleScript/bucklescript/issues/3855) I have different problems. Vs-code spawning me constantly with:
```
.npm-global/bin/ocamlmerlin-reason: 1: /home/misha-think/.npm-global/bin/ocamlmerlin-reason: Syntax error: word unexpected (expecting ")")
```
and
```
ocamlmerlin error: sh: 1: Syntax error: Unterminated quoted string
```
It doesn't look like the second error comes from my application as I have 3 small components with few quoted strings in total.

**Comment by mishaszu** [comment]
I tried to play with it a bit, but basically I always end with:
```bash
bash ocamlmerlin -version                                      ✔  1978  22:01:27
/mnt/c/Users/myuser/AppData/Roaming/npm/node_modules/ocaml-reason-wsl/bin/ocamlmerlin.bat: line 1: @echo: command not found
/mnt/c/Users/myuser/AppData/Roaming/npm/node_modules/ocaml-reason-wsl/bin/ocamlmerlin.bat: line 3: call: command not found
```
I am able to run this command only from `git bash`. It doesn't work in `PowerShell`, `WSL bash` & `WSL zsh`.
